model_2:
  Model_Best_params:
    ccp_alpha: 1.246255488017595e-05
    criterion: friedman_mse
    learning_rate: 0.05023154095974527
    loss: log_loss
    max_depth: 7
    max_features: sqrt
    min_impurity_decrease: 0.3272616355393083
    min_samples_leaf: 5
    min_samples_split: 10
    min_weight_fraction_leaf: 0.0010517756999873819
    n_estimators: 1000
    subsample: 0.848303690988349
    tol: 0.0014694784052536648
  Model_Best_params_score: 0.8547529356561
  Model_class: GradientBoostingClassifier
  Model_module: sklearn.ensemble
  training_artifact_file_path: artifact/stage04_model_training/model_eval_reports/gbt_study.csv
model_3:
  Model_Best_params:
    bagging_fraction: 0.9
    bagging_freq: 1
    feature_fraction: 0.5
    lambda_l1: 0.0
    lambda_l2: 0.0
    learning_rate: 0.030366618768579923
    max_depth: 10
    min_data_in_leaf: 1
    min_gain_to_split: 0.0
    n_estimators: 844
    num_leaves: 159
  Model_Best_params_score: 0.8795908240528394
  Model_class: LGBMClassifier
  Model_module: lightgbm
  training_artifact_file_path: artifact/stage04_model_training/model_eval_reports/lgbt_study.csv
model_5:
  Model_Best_params:
    bootstrap: true
    criterion: entropy
    max_depth: 8
    max_leaf_nodes: 10
    min_samples_leaf: 7
    n_estimators: 797
  Model_Best_params_score: 0.807731234225994
  Model_class: RandomForestClassifier
  Model_module: sklearn.ensemble
  training_artifact_file_path: artifact/stage04_model_training/model_eval_reports/xgboost_study.csv
