pay_x:
  columns:
    - PAY_0
    - PAY_2
    - PAY_3
    - PAY_4
    - PAY_5
    - PAY_6
  lower_bound: -2
  upper_bound: 4

bill_amt:
  columns :
    - BILL_AMT1
    - BILL_AMT2
    - BILL_AMT3
    - BILL_AMT4
    - BILL_AMT5
    - BILL_AMT6
  bins:
    - -350000
    - -1
    - 0
    - 25000
    - 75000
    - 200000
    - 2000000
  lower_bound: -350000
  upper_bound: 2000000

pay_amt:
  columns:
    - PAY_AMT1
    - PAY_AMT2
    - PAY_AMT3
    - PAY_AMT4
    - PAY_AMT5
    - PAY_AMT6
  bins:
    - -1
    - 0
    - 25000
    - 50000
    - 100000
    - 2000000
  lower_bound: -1
  upper_bound: 2000000
Age:
  columns:
    - AGE
  bins:
    - 20
    - 25
    - 30
    - 35
    - 40
    - 50
    - 60
    - 80
  lower_bound: 20
  upper_bound: 80
limit:
  columns:
    - LIMIT_BAL
  bins:
    - 5000
    - 50000
    - 100000
    - 150000
    - 200000
    - 300000
    - 400000
    - 500000
    - 1100000
  lower_bound: 5000
  upper_bound: 1100000